/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class Inflater {
  constructor()
  push(input: Buffer, flush?: boolean | undefined | null): Buffer
  reset(): void
}
